# Site settings
title: Thoughts of Gabriel Valle
header-img: img/home-bg.png
email: gvalle91@gmail.com
copyright_name: GabrielValle91
description: > # this means to ignore newlines until "baseurl:"
  hmm
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  GabrielValle91
learn_profile: GabrielValle91
email_username: gvalle91@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
